### ISSUE TITLE
[dev-dev] allow(dep)->toReceive()->with() not always read actual result

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#163]
The sample is on this: https://github.com/samsonasik/ApigilityConsumer/commit/4acba2cb463b9491198620076dbcc05fba2d6cf2 , Even I tried to use : 
```php
allow($this->client)
      ->toReceive('setOptions')
      ->with(['timeout' => 10000])
      ->andReturn($this->client);
```
It will always succeed. In actual object in spec, I passed 100 as timeout ( https://github.com/samsonasik/ApigilityConsumer/blob/master/spec/Service/ClientServiceSpec.php#L66 ):
```php
    public function callAPI(array $data, $timeout = null)
    {
            if (null !== $timeout) {
                   $timeout = (int) $timeout;
                   $this->httpClient->setOptions(['timeout' => $timeout]);
            } 
    }
```
The class is an `ClientService` that has `Zend\Http\Client as HttpClient` as dependency that injected to `__construct`

**Comment by jails** [comment]
In the `dev` branch `allow()` simply sets stubs which means:

```php
allow($this->client)
      ->toReceive('setOptions')
      ->with(['timeout' => 10000])
      ->andReturn($this->client);
```

simply means that `$this->client` is stubbed so that when it'll receive `toReceive()` with `['timeout' => 10000]` as argument, it'll returns `$this->client`.

Long story sort, `allow()` doesn't set any expectation. So you can set as many `allow()` as you want, specs will always pass.

So to check that a method (or a stubbed method) has **actually been called**, it's necessary to use `expect()`.

So if I get your example right I would write:

```php
    allow($this->client)->toReceive('send')->andReturn(Double::instance(['extends' => Response::class])); // Because we want to change the original behavior

    expect($this->client)->toReceive('setRawBody')->with(Json::encode($data['form-data']));
    expect($this->client)->toReceive('setOptions')->with(['timeout' => 100]);
    expect($this->client)->toReceive('setHeaders')->with($headers);
    expect($this->client)->toReceive('setUri')->with('http://api.host.url/api');
    expect($this->client)->toReceive('setMethod')->with($data['form-request-method']);

    $result = $this->service->callAPI($data, 100);
    expect($result)->toBeAnInstanceOf(ClientResult::class);
```

**Comment by samsonasik** [comment]
@jails Thank you :+1:, it works as expected now.
