### ISSUE TITLE
Invocation matchers should not be required before invocation

### ISSUE THREAD

**Issue by jasonmccreary** [kahlan/kahlan#166]
Invocation matchers should not be required before invocation.

### Current code
```php
describe('perform', function() {
        it('should format the app directory', function() {
            expect($this->utility)->toReceive('format')->with('app');
            $this->subject->perform();
        });

        it('should format the config directory', function() {
            expect($this->utility)->toReceive('format')->with('config');
            $this->subject->perform();
        });
});
```

### Expected code
```php
describe('perform', function() {
        beforeEach(function() {
            $this->subject->perform();
        });

        it('should format the app directory', function() {
            expect($this->utility)->toReceive('format')->with('app');
        });

        it('should format the config directory', function() {
            expect($this->utility)->toReceive('format')->with('config');
        });
});
```

Other BDD languages do not have this requirement as it breaks the flow of *setup-run-verify*.

**Comment by jails** [comment]
I didn't used a lot of mocking frameworks but this behavior is one implemented by RSpec. And I don't think it'll be possible to change that behavior easily for the following reason. 

With mocking frameworks you are explicitly creating test doubles which are "logging received calls". So it doesn't matter when calls are made, test doubles just log every call.

In Kahlan it wouldn't be possible to log every call made on every instance in memory at anytime mainly because of performance.

So `expect($this->utility)->toReceive('format')` lazy initialize some "mocking capabilities" on `$this->utility` only, so every call made on `$this->utility` in the futur will be logged.

**Comment by jasonmccreary** [comment]
Of course. But this flow is definitely not what is found in RSpec, Jasmine, Cedar, etc. Jasmine, for example, is `spyOn`, *call*, then `expect()`. It seems Kahlan is *spyOn*, `expect()`, *call*. Which is quite different.

Is there a way to write my *Expected Code* example in Kahlan?

**Comment by jails** [comment]
What do you mean by this flow is definitely not what is found in RSpec ? RSpec works the same way as Kahlan. If you take the following `user.rb` class:

```ruby
class User
  def something!
  end
end
```

And write the following spec:

```ruby
require 'user'

describe User do
  it 'passes' do
    user = User.new
    expect(user).to receive(:something!)
    user.something!
  end

  it 'fails' do
    user = User.new
    user.something!
    expect(user).to receive(:something!)
  end
end
```

The first spec passes but not the second. `expect(user).to receive(:something!)` expect `user` to receive `something!`, not to have been received.

**Comment by jasonmccreary** [comment]
If you setup `User` with `allow()`, then I most definitely would expect the second example to work. I've never written RSpec code like the first example. Not sure the point of that.

**Comment by jails** [comment]
I tried the following:

```ruby
require 'user'

describe User do
  it 'passes on a stub' do
    user = double()
    allow(user).to receive(:something2!)
    expect(user).to receive(:something2!)
    user.something2!
  end

  it 'fails on a stub' do
    user = double()
    allow(user).to receive(:something2!)
    user.something2!
    expect(user).to receive(:something2!)
  end
end
```
And the second spec fail the same way. Is it what you talked about ?

**Comment by jasonmccreary** [comment]
You're writing RSpec wrong. It's `expect(user).to have_received(:something2!)`

**Comment by jails** [comment]
Right now Kahlan only support the [RSpec's `to receive` matcher](https://relishapp.com/rspec/rspec-mocks/v/3-5/docs/basics/expecting-messages).

RSpec's `to have_received` is a different matcher which only work with spies and doubles. It can be implemented with Khalan coupled with `allow()` but the fact that it's not consistent and only works on doubles is confusing imo. Indeed `to have_received` has no naming indication indicating it must be used on doubles only.

**Comment by jasonmccreary** [comment]
Fair. I haven't written RSpec the way you have demonstrated, and honestly, don't see the value. All your doing is proving the next line of code (i.e. that you called `something2!`).

For me, this is a distinguishing feature for BDD style testing frameworks. if Kahlan doesn't support this, I'm not interested in using it at this time.

**Comment by jails** [comment]
Both `to receive` / `to have_received` are similar matchers. The first sets an expectation for the future and works for everything.
The second, on the contrary, checks the past but requires to creates test doubles for everything. And this point **is limiting** because it's not always possible to inject test doubles everywhere with some legacy code ex:

```php
it('checks if the welcome email is sent', function() {
    allow(Mailer::class)->toReceive('send')->andReturn(true);
    expect(Mailer::class)->toReceive('send')->with('user@domain.com', 'Welcome');
    $user = new User();
    expect($user->save())->toBe(true);
});
```
And it wouldn't be possible to do the other way round since it would require to inject a double for the `Mailer` instance in the `User` model which is not always possible.

And since it's also not possible to log calls for every classes and instances at runtime to be able to check what has been called at any time, `toReceive` was the way to go in respect of RSpec and it's totally compatible with BDD.

**Comment by jasonmccreary** [comment]
If Kahlan is a testing framework biased towards testing legacy code, I respect your decision not to support this. However, I find that to be a limitation as someone who is not writing legacy code. I understand it's not easy to track message calls, but I'm having a hard time believing it's *not possible* as every other modern BDD-style testing framework has found a way to do so.

**Comment by jails** [comment]
Indeed it's not possible to log calls for every classes and instances at runtime for some performance and memory concerns. And RSpec is no exception to the rule, `to have_received` only works on doubles not everything.

But if you prefer a `spy()` / `toHaveBeenCalled()` mechanism it's totally possible to mark the class/instance to be spied first so only calls on this class/instance will be logged. 

However `spy()` / `toHaveBeenCalled()` didn't respect the RSpec style that's why I preferred to choose the RSpec's `to receive` way.

Anyhow Kahlan is flexible enough to support custom matchers. So it's up to you, you can totally split the actual `ToReceive` matcher to use your own. Everything is in `ToReceive` so it shouldn't be that hard to split it in two parts so you can mark the class/instance to spied first (using a kind of `spy()` function), then resolving calls with a `toHaveBeenCalled()` custom matcher. 

Anyway RSpec's `to receive` probably changes your habits but it's not limiting.
