### ISSUE TITLE
Reopenning of #106 (toBeOneOf)

### ISSUE THREAD

**Issue by Kaijiro** [kahlan/kahlan#170]
Hey,

I leaved a comment on [this issue](https://github.com/kahlan/kahlan/issues/106) but as it's already closed I think you didn't see it (not blamming you).

The topic of this issue by @tyranron was to create a toBePartOf matcher inside of Kahlan. I found a real example where this can be usefull :

You retrieve an entity via an API and this entity may have a field that must be one of the value of a known array. For a real case, I retrieve promotions from an API inside which there is a field named "promotion_type". This field can be only be "PERCENTAGE" or "PRICE".

Given this situation, I think every case where we get an entity which have this type of field which is not driven by an enum can have use of this type of matcher.

**Comment by samsonasik** [comment]
@Kaijiro I've created PR #171 for it ;)

**Comment by jails** [comment]
We'll probably need to think large on this one. The main objective here is to keep the number of matchers as small as possible to make sure people won't forget the correct one to use. And when you are not using a matcher that much, you tend to forget it. That's the case with PHPUnit for example where approx. 80% of matchers are used only 20% of times (checked on a ZF project) which leads to approx. 40% of matchers which wasn't used at all.

If we add `toBeOneOf()`, to be consistent we will need to add `toEqualOneOf()` as well. And in a same logic why not including their array counter part ? i.e. checking if a array is included in another ?

`toContain()` has been added because it was a Jasmine matcher but it has the same drawback in a way.

So unless we can find minimal set of matchers to solve the whole range of use case, staying close to the Jasmine  DSL is imo the best option.

**Comment by tyranron** [comment]
@jails we understand your concerns. * I think @Kaijiro and @samsonasik don't mind if I'll answer for them =) *

But it's all about tests readability. Yes, situation `expect($expected)->toContain($actual)` is still readable, but it really frustrates to have `expect($expected)`. We are used to see `expect($actual)` in our tests. It's the way we read things, it's the way we think about something. Having `expect($actual)->toBe...` really simplifies understanding what we really are testing here.
Nothing more.
And here I'd better choose to have some sugar than fighting my human nature all the time. =)

As for use frequency, it's quite common situation to test ENUM-like values in my code, for example. So I really implemented it as custom matcher and using it all the time.
Bad part is absence of type hinting (and autocompletion as result). But it's okay. Actually common situation for PHP code and I'm used to it.

**Comment by jails** [comment]
> but it really frustrates to have expect($expected)

I totally agree, `expect($actual)` is the way to go, `toContain()` shouldn't be used the other way round.

I completely understand the need of such matcher. But I actually don't know what should be the best approach.

Should we add `toBeOneOf()` or `toBeIn()`? with `==` or `===` under the wood ? How many matchers like this one could be created to cover almost all usages ? Does `toBeIncludedIn()` would make sense for arrays ? What is the fixed limit ? And the fact there's no equivalent in Jasmine nor RSpec doesn't really help here.

So it's not like I don't want to add new matchers but I don't want to screw everything up by not taking the time to think large.

The fact we are all coding differently leads to different needs. Maybe the best option would be to create some repositories like `kahlan-matcher-to-be-one-of`  to get a broader view of matchers needs. Then we should be able to figure out a minimal set of matchers to cover needs.

**Comment by samsonasik** [comment]
@jails how about create new repository named `kahlan/dxmathers` so people can make PR and propose new developer experience machers ? , so, when it created, people can do:
```
composer require kahlan/dxmatchers
```
and register what they needs:
```php
Kahlan\Matcher::register('toBeOneOf', 'Kahlan\Dxmatchers\ToBeOneOf');
```

**Comment by Kaijiro** [comment]
I think @samsonasik is a nice idea. 

People would be able to contribute and we could debate around all matchers added by the commnuity so we could decide (with you in priority @jails , of course) if the matcher and it's others forms are used enough to be integrated in the "real" Kahlan repository.

If they are not, they would stay in the dxmatchers repo so they still can be used by the community when they will be needed (without the eternal need of created our own matcher).

**Comment by tyranron** [comment]
@jails I understand you so much. Perfectionism is a pain for making choice, but a blessing (kind of) for product =)

#### Turning back to thread theme...
I think in this case `toBeOneOf()`(`==`)/`toEqualOneOf()`(`===`) is enough. With semantic `expect(item)->toBeOneOf([item1, item2, ...])` just like PHP `in_array()` function. Why? Because  it was requested twice (by me and @Kaijiro) and in both cases it was checking value against some enumeration.
If we think about it one step deeper...
PHP does not have enums, so it's natural that there are no matchers for them, because matchers are built on top of language type system first of all. But business logic, however, does have enumerations quite often (developers emulate them in PHP code via arrays, class constants, usual constants and other stuff). So, enums exist as a type in business logic abstraction, and in test we are used to operate with business logic abstractions, not language primitives. So, in real we do have enum "type", but don't have matcher for it.

As for
> Does `toBeIncludedIn()` would make sense for arrays ?

don't really thinks so. As I wrote before `toBeOneOf()` is not about arrays, it's about enums (arrays are just a way to express enums in PHP code).
Still, we can have `->toBeContainedIn()` which will directly mirror `toContain()` marcher. Just like common alias, but with reversed `$actual` and `$expected` (a "reverse alias" ? =) ). It can be quite handy too.

Also...
To make difference between enum and array matchers, maybe there is some sense to make enum matcher to be not a function that accepts an array as argument but a function that accepts many arguments (maybe > 1 args min?)? Something like:
```php
expect($actual)->toBeOneOf($expected1, $expected2, ..., $expectedN);
// and for enum described by array
$expected_ones = [$expected1, $expected2, ..., $expectedN];
expect($actual)->toBeOneOf(...$expected_ones);
```

#### Some thoughts about amount of matchers...
>The main objective here is to keep the number of matchers as small as possible to make sure people won't forget the correct one to use. And when you are not using a matcher that much, you tend to forget it. That's the case with PHPUnit for example where approx. 80% of matchers are used only 20% of times (checked on a ZF project) which leads to approx. 40% of matchers which wasn't used at all. 

My opinion is that instead of solving "forget the correct" problem it's better to express matchers in almost all possible natural ways (via aliasing, semantic reversion, duplication, etc), so that developer does not need to think about correct matcher, he just writes almost natural english and gains what he wants. In that case it's okay that we have big amount of matchers and some of them are quite rarely used (or even not used). The only problem that they must express their matching in most natural way and be intuitive (so matchers design still matters very much =) ).

#### About separate repo for experimental matchers
 +1 definitely
Design always must be checked with time before it can be called good and applied to fundamentals. And we will have options for experiments.

**Comment by samsonasik** [comment]
here the new repo for it: https://github.com/kahlan/extra-matcher ;)

**Comment by jails** [comment]
@tyranron, I'm totally agree with you.
So we can start adding additionnal matchers here https://github.com/kahlan/extra-matcher and see how far we get with that.
`expect(item)->toBeOneOf([item1, item2, ...])` is probably the most obvious syntax for now so let's start with that.
In regards of `->toEqualOneOf()` it doesn't seem to be appropriate to the "enum" use case. Anyway if you feel like it also has some valid usage, feel free to add it there.
