### ISSUE TITLE
istanbul coverage for interface method

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#175]
I'm not sure if it is an istanbul coverage or kahlan's istanbul reporter coverage issue. The `Functions` column shown red. This is what shown for html generation with istanbul:
![istanbul-coverage](https://cloud.githubusercontent.com/assets/459648/19413834/5f191114-9364-11e6-8a77-dcef29d3510e.png)
the method in interface hit by class spec: https://github.com/sitrunlab/learn-kahlan#get-html-report

**Comment by jails** [comment]
Imo interfaces shouldn't even appear in reporting.

**Comment by samsonasik** [comment]
is it reporter issue or the interface should be excluded in kahlan config?

**Comment by jails** [comment]
It's related to how PhpDbg/Xdebug collect code coverage. They shouldn't mark lines in interfaces as "covered code". By the way a lot of "non-sense" collected by those low level drivers has been solved by Kahlan so I guess we will need to find a way to filter them out.

**Comment by jails** [comment]
I guess we should `unset($this->_coverage[$file])` https://github.com/kahlan/kahlan/blob/master/src/Reporter/Coverage/Collector.php#L366 before the `return` statement to remove the coverage of a file when an interface is detected. 
But since `->export()` and `->metrics()` on `Collector` are independents, I guess this trick will only work if `->metrics()` is called before `->export()`.

**Comment by samsonasik** [comment]
Ok, just info, the interface only shown if using istanbul. It disappeared if using lcov

**Comment by jails** [comment]
Weird they should all work the same way. They are all exporting coverage using `$collector->export()`.

**Comment by jails** [comment]
Fixed in 3.0.2 !

**Comment by samsonasik** [comment]
@jails Thank you, I confirm it fixed by update to 3.0.2.

**Comment by jails** [comment]
:+1:
