### ISSUE TITLE
Warning: Cannot bind an instance to a static closure in ./vendor/kahlan/kahlan/src/Scope.php on line 457

### ISSUE THREAD

**Issue by MarcelloDuarte** [kahlan/kahlan#192]
Hello kahlan community! :wave:

This happens on every run for me, when running kahlan with hhvm. I imagine there is no official support, but this is the only bug I've come across. Writing kahlan tests with hhvm is fun as we can use their lambda shorter syntax, plus I am writing functional code in hack, so this is such a great fit as testing tool, it would be a shame not to use it.

**Comment by jails** [comment]
Hi, indeed Kahlan is currently only able to parse PHP7 syntax. I recently removed `hhvm` from `.travis.yml` only because of the following issue https://github.com/facebook/hhvm/issues/7297
But once a new `hhvm` version will be tagged with the related fix merged, hhvm will be back in the CI.

As regards of your issue, it doesn't looks like `hhvm` related. Seems more that your suite is included through a static function somehow. And because of a [php "nonsense"](https://bugs.php.net/bug.php?id=64761) it can be an issue with Kahlan because of the bug-for-bug parity with hhvm.

[This repository](https://github.com/crysalead/text) is a small example of how I organize my specs suite and [I didn't notice any error with hhvm](https://travis-ci.org/crysalead/text).

 Would it be possible for you to create a sample repo generating this issue ?

**Comment by jails** [comment]
Were you able to solve it by yourself @MarcelloDuarte ?

**Comment by MarcelloDuarte** [comment]
@jails I was not, sorry :( I cannot see from your repo example what I am doing different. I am pushing my work [here](https://github.com/MarcelloDuarte/cathacks) for you to have a look, if you don't mind. Thanks in advance.

**Comment by jails** [comment]
@MarcelloDuarte not sure to get how auto-loading works with hhvm, looks like as soon as you are using the `<?hh` tags, hack is loading all `*.hh` files in the directory (like the ones in the `examples` directory) which generate a bunch of errors.

Anyway, as regards of the binding issue, looks like it's related to the lambda syntax `==>`. Contrary to `function(){}`, lambdas seem to be static functions in HHVM. The good news is this re-binding is almost optional for Kahlan so I simply ignore warning for now and I'll probably remove this requirement in the next version.

So it has now been fixed in the 3.0.3 relase.

**Comment by MarcelloDuarte** [comment]
Thank you 👍
