### ISSUE TITLE
can't stub (new Aclass())->method() in php 5.6

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#200]
repo to reproduce: https://github.com/samsonasik/kahlan-issue-new
travis result show the issue: https://travis-ci.org/samsonasik/kahlan-issue-new/builds/183440258

It works on php7

**Comment by jails** [comment]
The [uniform variable syntax](https://wiki.php.net/rfc/uniform_variable_syntax) in only available since PHP 7.0

So this syntax:
```php
(new AClass())->method();
```
is invalid on PHP5.

So the only way to make it works for both PHP5/PHP7 is to write it that way:

```php
$instance = new AClass();
$instance->method();
```

**Comment by samsonasik** [comment]
no no, this works on php 5.6  based on 3v4l: https://3v4l.org/7F23M

**Comment by jails** [comment]
Ah yeah sorry, what I meant is the following:

To be able to patch classes the Just In Time patcher rewrite the code that way https://3v4l.org/UBSUR

Unfortunately the uniform variable syntax is only supported by PHP>=7 that's why `($something ? $something : new $classname)->method()` generates an error on old PHP versions.

There was no issue with Kahlan 2.x because it doesn't support instances replacement. Not sure it's possible to find a workaround for this

**Comment by jails** [comment]
@samsonasik would you mind testing the dev branch ? I [modified the JIT patcher](https://github.com/kahlan/kahlan/commit/b4eb1a4c693094a6e7d1c5c42696e6d2e7e97604) so PHP<7 won't use the substitution feature anymore. It's a pitty for PHP<7 but a test framework shouldn't influence on how code should be written.

PS: cache files must be cleared first.

**Comment by samsonasik** [comment]
@jails it working now with travis green in php 5.6: https://travis-ci.org/samsonasik/kahlan-issue-new/builds/183624335 with `"kahlan/kahlan": "dev-dev"`.

Thank you ;)

**Comment by jails** [comment]
Ok great so I'll update the documentation to indicate that the substitution feature is a PHP>=7 from now.
