### ISSUE TITLE
Incomplete expectations cause test completion but silent failure

### ISSUE THREAD

**Issue by madhancock** [kahlan/kahlan#223]
`expect('ACTION');` will complete a testing build but will silently fail with a 255 exit code.

In CI the build will fail the test, however the output will show that the tests passes. There is no output indicating there is a problem without checking the exit code. Finding the problem is made very difficult.

**Comment by jails** [comment]
Indeed quite tricky, thanks for reporting.
Since 3.x version we now have the pending concept for specs.
So I changed the behavior so that a spec will be marked as pending when an expectation is incomplete.
The fix is now on the dev branch https://github.com/kahlan/kahlan/commit/f6b109389b7d3dfc88994d732cb3cb7f238129d1
