### ISSUE TITLE
Method stubbing doesn't work in 4.0.5

### ISSUE THREAD

**Issue by kilbiller** [kahlan/kahlan#281]
Hi,

I just updated to 4.0.5 from 4.0.4 and most of my tests are throwing now. They fail on both window 10 and ubuntu 16.04 (inside a docker container).
Basically there is a database call in a method that i'm stubbing that now gets called anyway.

**Comment by jails** [comment]
Hi ! Thanks for reporting.
It's difficult to answer here.
Can you give me a sample repo so I can investigate ?

**Comment by kilbiller** [comment]
So here's the repo : https://github.com/kilbiller/kahlan-repro

Sorry, since i've no idea where the bug might be coming from that was the smallest i could do.

**Comment by jails** [comment]
Hello!
The `kahlan-config.php` file is used to configure Kahlan so when this file is ran, all patching stuff are not configured yet. So if you need to load some classes in `kahlan-config.php` you will need to rewrite it that way:

```php
<?php
use Kahlan\Filter\Filters;
use Cake\Model\ConnectionManager;

use Kahlan\Filter\Filter;

$commandLine = $this->commandLine();

$commandLine->set('spec', 'tests');
$commandLine->set('grep', '*Test.php');
$commandLine->set('src', ['app/Controller', 'app/Model']);

Filters::apply($this, 'run', function ($chain) {

    // Fix calls to redirect()
    define('FULL_BASE_URL', 'http://test.invityou.com');

    include 'app/webroot/kahlan.php';

    restore_error_handler();
    restore_exception_handler();

    // Remove db connection
    ConnectionManager::drop('default');

    return $chain();
});
```

When the `'run'` filter is called, Kahlan is up so you can start loading what you want, otherwise they will be loaded without any patching.

The other issue is that Kahlan must be used as a drop-in replacement of Composer. So the following line in your `app/webroot/kahlan.php` must be removed:
```php
require dirname(__DIR__, 2) . '/vendor/autoload.php';
```
Or at least you can write:

```php
if (!defined('KAHLAN_VERSION')) {
	require dirname(__DIR__, 2) . '/vendor/autoload.php';
}
```

Indeed if you are additionally loading the Composer autoloader, it'll put itself first in the autoloaders stack which will bypass the Kahlan's one.

I don't really get why it worked in 4.0.4 but it definitely shouldn't.

**Comment by kilbiller** [comment]
Yeah that worked perfectly, thanks. 
Since it worked from the start I assumed the code was correct. If you ever find what exactly allowed this to work before I'd be interested to know.
