### ISSUE TITLE
Support for never return type (PHP 8.1+)

### ISSUE THREAD

**Issue by michalfelski** [kahlan/kahlan#409]
The code generated by Kahlan contains an illegal „return" in functions and methods that have a "never" type.  This results in an error:
PHP Fatal error: A never-returning function must not return in ...
At the moment, Kahaln is an obstacle to using this PHP functionality.

I'm not sure how exactly it should work, or what restrictions need to be put in place, but I invite you to discuss.
It would still be nice to be able to create a spy on these methods, but ->andReturn() doesn't make sense for them.

**Comment by michalfelski** [comment]
The easiest way is replacing "never" with "void" when code is generated until it breaks signature when method overrides parent or it is implementation of the interface :)

**Comment by jails** [comment]
If I get it right the never type require an exit() or die() call somehow.
It's possible to handle them with the `Quit` plugin to return an exception instead of exiting the process.

I added the following in the dev branch to handle the never type.
https://github.com/kahlan/kahlan/commit/4276f2f3d3852c3a299888098ecd80b0091be79f#diff-11276323115a69c417f67dba6efcf525db29f062902c991f7e2763954d70fae2R96

You should be able to test it by using `kahlan/kahlan:dev-dev` as dependencies.
Make sure once updated to run `kahlan -cc` to clear caches so they can be regenerated.

Does that solve the issue you were talking about ?

**Comment by michalfelski** [comment]
Thank you for your super fast reply. That patch completely solves the problem. 
For accuracy never specifies functions that call exit(), throw an exception or are an infinite loop. All these cases work correctly with this change.

**Comment by samsonasik** [comment]
@michalfelski thank you for verify, I will create new release for it 👍

**Comment by samsonasik** [comment]
kahlan 5.2.3 released for it https://github.com/kahlan/kahlan/releases/tag/5.2.3
